### ISSUE TITLE
Kemal Example

### ISSUE THREAD

**Issue by crisward** [Sija/raven.cr#16]
Thanks for this module BTW, it looking good so far.

It would be good to see a kemal example. I've required this into my app, but the only exception reported are those I am explicitly sending with raven capture. I'm guessing I need to chuck `Raven.capture(exception)` into my 500 error handler?

**Comment by Sija** [comment]
You're right, there's lack of proper docs. atm for what's worth there are API docs you can find at https://sija.github.io/raven.cr/.

Specific example you mentioned is hidden inside of [`Raven::Kemal::ExceptionHandler`](https://sija.github.io/raven.cr/Raven/Kemal/ExceptionHandler.html) documentation.

**Comment by Sija** [comment]
Does linked example answers your question?

**Comment by crisward** [comment]
I think so...

I had to do this. Not sure if it should be added to your docs (if I'm doing it correctly)

```ruby
require "kemal"
require "raven"
require "../lib/raven/src/raven/integrations/kemal.cr"
add_handler Raven::Kemal::ExceptionHandler.new

# example exception
get "/"  do |env|
  1 / 0
end

Kemal.run
```
Does this look correct ?

**Comment by Sija** [comment]
Quite correct, tho' I'd simplify it a bit, like:

```cr
require "kemal"
require "raven"
require "raven/integrations/kemal"

add_handler Raven::Kemal::ExceptionHandler.new

# example exception
get "/"  do |env|
  1 / 0
end

Kemal.run
```

**Comment by Sija** [comment]
I'm closing this issue, since it looks like you've got the answer to your question.
