### ISSUE TITLE
No JSON data was found

### ISSUE THREAD

**Issue by viix** [Sija/raven.cr#18]
I got this error when send event to sentry server.
ERROR -- sentry: Unable to record event with remote Sentry server (Raven::Transport::HTTP::Error - No JSON data was found)

I am very confused.
does anybody know why?

**Comment by Sija** [comment]
Could you post the offending code so we can track down the problem?

**Comment by viix** [comment]
I just new an error and capture it.

e = InvalidArgumentError.new(message: "some error")
Raven.capture(e)

**Comment by viix** [comment]
for your convenience to find the problem,
I create a repo that is extracted from my usage. Here it is. https://github.com/viix/demo

and my sentry server is build from the official docker on premise. the server version is 8.18.0

**Comment by Sija** [comment]
Just tried and it works for me:

```
I, [2018-04-19 19:08:11 +02:00 #26534]  INFO -- sentry: Raven 0.9.0 ready to catch errors
I, [2018-04-19 19:08:11 +02:00 #26534]  INFO -- sentry: Sending event 38150b9c014d4d9986f72812212310c7 to Sentry
```

Please reopen if you still encounter this error.
