### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by psikoz** [Sija/raven.cr#30]
Hey, @Sija   I designed a logo for contribution. 

a sentry-style logo. What do you think about that?

![raven](https://user-images.githubusercontent.com/40601249/42401832-2a3bead2-8180-11e8-8efb-fb3e507383e6.jpg)

**Comment by Sija** [comment]
I like it except the font, could you find something less... curvy? :)

**Comment by Sija** [comment]
In the end raven is a... ya know, predator ;)

![kisspng-common-raven-t-shirt-drawing-clip-art-bee-5abddb7fe19700 143351641522391935924](https://user-images.githubusercontent.com/988/42909880-d82c604a-8ae5-11e8-85ff-70cdf313aacd.png)

![expo_the-raven_10561-1200x675-b-p-ffffff](https://user-images.githubusercontent.com/988/42909861-d1570f86-8ae5-11e8-83b4-e8bc4b9e0e6e.jpg)

**Comment by Sija** [comment]
@psikoz Anything going on with this? If not, please close this issue.

**Comment by psikoz** [comment]
I am sorry but I can not design anything about it.
