### ISSUE TITLE
Discarded invalid value for parameter 'exception' 

### ISSUE THREAD

**Issue by greenbigfrog** [Sija/raven.cr#44]
I'm getting getting following error on all Events:
```
There was 1 error encountered while processing this event
Discarded invalid value for parameter 'exception' 
```

Any ideas what could be causing this?

**Comment by Sija** [comment]
That's odd...
Are there any details about the actual value?
Could you post perhaps the raw json for inspection here?

**Comment by Sija** [comment]
Any news regarding this?

**Comment by greenbigfrog** [comment]
Haven't seen it anymore. Might have been a temporary sentry issue. Closing for now.
