### ISSUE TITLE
`send_event` tries to connect even if DSN not set

### ISSUE THREAD

**Issue by straight-shoota** [Sija/raven.cr#54]
When no DSN is set (for example when running specs), raven should be disabled. This works for error reporting, but not for sending events:
```
sentry: Unable to record event with remote Sentry server (Exception - Unknown transport scheme ''): lib/raven/src/raven/client.cr:0:9 in 'transport'
lib/raven/src/raven/client.cr:61:9 in 'send_event'
lib/raven/src/raven/instance.cr:110:7 in 'send_event'
lib/raven/src/raven/instance.cr:109:5 in 'send_event'
lib/raven/src/raven.cr:10:5 in 'send_event'
```

I suppose `Client#send_event` should check for `Connection#valid?` (or a specific method for sending events?) and just silently exit if no DSN is configured.

**Comment by Sija** [comment]
> This works for error reporting, but not for sending events:

Could you expand bit more on this part?

**Comment by straight-shoota** [comment]
When no `DSN` is configured, raven won't try to send errors (this is indicated by `configured not to capture errors: DSN not set` on startup). But it still tries to send events passed to `Raven.send_event`. This should just be a noop when no DSN is configured.

**Comment by Sija** [comment]
> But it still tries to send events passed to `Raven.send_event`. This should just be a noop when no DSN is configured.

That's correct and I'll do fix that, I'm curious though how do you end up calling `Raven.send_event`?
Is it some call within your code?

**Comment by straight-shoota** [comment]
Yes, I use it to track some events.
