### ISSUE TITLE
Gauging Interest in Performance Monitoring Capabilities

### ISSUE THREAD

**Issue by stephendolan** [Sija/raven.cr#84]
Hey there!

Thanks so much for this lovely library. It has saved me many production headaches thus far working with my Lucky apps, and the next horizon I'm trying to get to is some basic server-level application performance monitoring. Sentry has actually rolled out some really nifty performance stuff:

https://develop.sentry.dev/sdk/performance/

I've been digging through the code for a bit, and while it seems like they're using a relatively simple backing of the Event object, I can't seem to get any performance data sending over with some `Raven.capture` trickery. Is this performance tracing something that the maintainers would be willing to have included in this library?

If so, any guidance on where I should start with a pull request would be really helpful, in terms of architecting/setting it up in a way that's most in line with how the project is structured.

**Comment by Sija** [comment]
Hi @stephendolan!

Implementing performance monitoring features seem pretty sweet indeed and if possible I'd be happy to include them within the raven shard, sure.

> I've been digging through the code for a bit, and while it seems like they're using a relatively simple backing of the Event object, I can't seem to get any performance data sending over with some `Raven.capture` trickery. Is this performance tracing something that the maintainers would be willing to have included in this library?

AFAIR they're using several other concepts to back it up - i.e. Transaction, Span. These would have to be designed into the library as well I guess.

**Comment by stephendolan** [comment]
Awesome! I've been wanting to become more familiar with the intervals of this library, so I'll do some digging and submit a PR soon™️!
