### ISSUE TITLE
Is it possible to capture values along with stack trace ?

### ISSUE THREAD

**Issue by dinko-pehar** [Sija/raven.cr#85]
Hello.
I have tested your plugin on one of our source code and it works perfectly by displaying stack trace. It's displayed properly in Sentry.
However, what I would like also to have values of certain objects before crash. Is it possible to have these values displayed somehow by modifing `Raven` maybe ? Something like [inspect](https://crystal-lang.org/api/1.1.0/Exception.html#inspect(io:IO):Nil-instance-method) maybe ?

**Comment by Sija** [comment]
I'm not sure if I understand you correctly, but if you want to attach additional data along with the event, you can use for that `tags` or `extra`, which accept pretty much arbitrary metadata.

**Comment by dinko-pehar** [comment]
I'll try that in future. I have seen `extra_context` in README.md, but Context in `For more information, see Context.` is broken link so that's why I'm asking this.
